# Generated by Django 4.1.7 on 2023-03-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_alter_measurement_options_alter_sensor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={},
        ),
    ]
